### ISSUE TITLE
Why not in Laravel?

### ISSUE THREAD

**Issue by ghost** [mybb/mybb.com#4]
If you guys are using the Laravel Framework for 2.0, why not start with building the website in Laravel as well?

**Comment by Stefan-MyBB** [comment]
Jekyll offers all we need and static files are much faster than any PHP framework.

**Comment by pkill37** [comment]
I thought of it, especially for the docs. Dayle's [docs-reader](https://github.com/daylerees/docs-reader) (used to build Laravel's documentation) is exactly what I had in mind.

I guess it all comes down to the fact that GitHub Pages hosts the site for **free** with practically 100% uptime. This is great for us because we don't have to keep two other websites up and running.

**Comment by ghost** [comment]
Ah, didn't see you guys was building it off of that!
