### ISSUE TITLE
Issue appropriate redirects

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb.com#7]
The following is a list of redirects which need to be created so we don't end up with broken links.

/downloads/\* -> /download/*
/about/mybb -> /about/
/about/community -> ? (Doesn't exist anymore. Redirect to /about/?)
/about/apply -> /get-involved/

/support -> ? (This page should probably exist?)

We need to also figure out the best way to redirect the pages as we have limited options.

**Comment by justinsoltesz** [comment]
I've already set up redirects for a number of pages using a simple HTML redirect. From what I understand this is pretty much the only option. See the redirect.tpl layout.

A few are already set up (such as downloads, though it doesn't currently use the baseurl) though apparently I missed several.

**Comment by nmalcolm** [comment]
/features/tasks -> /features/13-task-scheduling/
/features/db-support -> /features/15-dbms-support/
/features/warning -> /features/11-warning-system/
/features/mass-mail -> /features/12-mass-mail-and-newsletters/
/features/reputation -> /features/09-reputation/
/features/calendar -> /features/08-calendars-and-events/
/features/threads -> /features/07-threads-posts-and-polls/
/features/promotions -> /features/10-user-promotions/
/features/themes -> /features/05-template-and-theme-editor/
/mailing-list/ -> Redirect to Twitter maybe?
/contact/piracy -> /contact

That seems to be all that's left.

**Comment by JordanMussi** [comment]
> /mailing-list/ -> Redirect to Twitter maybe?

Or possibly a sub page of get involved for social networks?

**Comment by nmalcolm** [comment]
Get Involved is more for things like MyBB development and support. We don't link to the mailing list anymore but pointing it to our Twitter account is the next best thing.

/downloads/merge-system/license-liability -> /download/merge-system/license/

**Comment by JordanMussi** [comment]
I would like to reopen this issue in light of the recent GitHub blog post: https://github.com/blog/1797-repository-metadata-and-plugin-support-for-github-pages

> [Jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from) provides an easy way to redirect visitors to the proper url when a post or pages's filename changes.

This can now be made use of instead of using HTML tags, as it would also redirect non-browsers to the correct locations. However redirects to twitter, for example, would not work with this new method.

https://help.github.com/articles/redirects-on-github-pages will be a helpful page for this process.

---

Edit: Should a new ticket be created for this or just reopen this one?

**Comment by justinsoltesz** [comment]
I'll take care of this.

**Comment by justinsoltesz** [comment]
Well it seems there's an issue with the implementation...everything redirects to the root instead of the correct page. For instance, going to http://mybb.github.io/mybb.com/downloads/ redirects to http://mybb.github.io/download/

Edit:

I'm going to leave as updated for now in hopes that GitHub fixes the issue soon (I've contacted them about the bug)

**Comment by justinsoltesz** [comment]
I haven't heard anything back from GitHub about the issue with jekyll-redirect-from so I've reverted the commit for now.

**Comment by JordanMussi** [comment]
Try following it up. It's possible your email has been lost in the mix. I get replies within 24-48 hours of sending through the [contact form](https://github.com/contact).

**Comment by JordanMussi** [comment]
This should work since we're going to implement this at http://www.mybb.com....
